# Generated by Django 4.1.7 on 2023-03-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('District', models.CharField(blank=True, max_length=30, null=True)),
                ('Location', models.CharField(blank=True, max_length=30, null=True)),
                ('Departments', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.ImageField(upload_to='Profile')),
            ],
        ),
    ]
