# Generated by Django 4.1.7 on 2023-03-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldb',
            name='Departments',
        ),
        migrations.AddField(
            model_name='hospitaldb',
            name='Contact_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
