# Generated by Django 4.1.7 on 2023-03-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0002_remove_hospitaldb_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldb',
            name='Image',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
