# Generated by Django 4.1.7 on 2023-03-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0003_alter_hospitaldb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Doctor_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
                ('Contact_Number', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='DoctorsImages')),
            ],
        ),
    ]
